### ISSUE TITLE
ton command hangs then opens the file in same pane

### ISSUE THREAD

**Issue by slacksystem** [trevarj/tmux-open-nvim#2]
Hi, when I type `ton abc.txt` (or any file) it hangs for about 30 seconds, then opens the file in the same pane, in a new instance of nvim, even though there are others running. I'm calling ton from zsh but I have bash installed. I'm using lunarvim, and my `EDITOR` is set to `lvim`, perhaps that's the issue? If so is there any way to make that compatible?

**Comment by trevarj** [comment]
Hi, you can try changing `nvim` to `lvim` on these lines on the local installation of `ton`- 
https://github.com/trevarj/tmux-open-nvim/blob/0c46b96b0d911ebcb444c721e4382303cfc64653/scripts/ton#L35C3-L36 and https://github.com/trevarj/tmux-open-nvim/blob/0c46b96b0d911ebcb444c721e4382303cfc64653/scripts/ton#L44
and by verifying if a running instance of `lvim` still uses the `nvim` naming convention for the listening sockets, e.g `/run/user/1000/nvim.1624238.0`

**Comment by trevarj** [comment]
Closing as stale
