### ISSUE TITLE
Seeing selection modal when there's only one neovim pane in the window

### ISSUE THREAD

**Issue by dkarter** [trevarj/tmux-open-nvim#7]
Hi!

Thanks for this plugin, it looks really useful :)

I've installed it and have been testing it out, here's my config: 
https://github.com/dkarter/dotfiles/blob/eb25d8a90703d524c71dbe09b861e78710999e09/config/tmux/tmux.conf#L251-L253

The way I work, is I have multiple sessions open, and each session will have a neovim instance in one of the tabs (tmux windows).

I noticed that tmux-open-nvim will show me a modal for selecting an instance, even if there's only one neovim instance in the current window. I'm not sure if this is intended, but it feels unnecessary to me - I most likely want to open the file in the current window and not in some other session.

Here's a quick video showing the problem:

https://github.com/user-attachments/assets/b6c57b47-92da-4b20-bb02-0ce6301cff44

I have another session with a single window that has two `nvim`s in it, and those are picked up in the pop up window for some reason.

If I close the other session, it works as I expect:

https://github.com/user-attachments/assets/e0498604-04d5-4cbd-aad8-714766e8e942

**Comment by trevarj** [comment]
Thanks for reporting!

Indeed it was pretty buggy and my original intention was to make it not span across tmux sessions, which seems like overkill.

I pushed a commit that should fix it. Keep your config the same and give it a try.

**Comment by dkarter** [comment]
Oh that's perfect, thank you so much! Confirmed the fix!
